apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifecycle
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lifecycle
  template:
    metadata:
      labels:
        app: lifecycle
    spec:
      initContainers: # first container running to initialize databse for instance
      - name: init
        image: yulypso/node-app:v0.0.2
        command: ['sh', '-c', 'sleep 10']
      containers:
      - name: lifecycle-container # main container to run
        image: yulypso/node-app:v0.0.2
        command: ['sh', '-c', 'echo $(date +%s): Running >> /timing && echo "The app is running!" && /bin/sleep 120']
        livenessProbe: # health check; restart pod if lifeless
          exec:
            command: ['sh', '-c', 'echo $(date +%s): livenessProbe >> /timing']
          initialDelaySeconds: 35
          timeoutSeconds: 30
        readinessProbe: # health check: remove IP if unaccessible 
          exec:
            command: ['sh', '-c', 'echo $(date +%s): readinessProbe >> /timing']
          initialDelaySeconds: 35
        lifecycle:
          postStart: # after initContainer starts
            exec:
              command: ['sh', '-c', 'echo $(date +%s): postStart >> /timing && sleep 10 && echo $(date +%s): end postStart >> /timing']
          preStop: # before main container stops
            exec:
              command: ['sh', '-c', 'echo $(date +%s): preStop >> /timing && sleep 10']
