apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels: 
    app: my-node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels: 
        app: my-node-app
    spec:
      containers:
      - name: node-app
        image: yulypso/node-app:v0.0.1
        ports:
        - containerPort: 3000
      nodeSelector: # to run on a specific node within the cluster
        hardware: high-spec