apiVersion: v1
kind: ServiceAccount # user admin
metadata:
  name: admin-user
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding # to bind the user with the role
metadata:
  name: admin-user
roleRef: # the admin role
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects: # the user binded
- kind: ServiceAccount
  name: admin-user
  namespace: kube-system
