apiVersion: v1
kind: ReplicationController
metadata:
  name: node-app-controller
spec:
  replicas: 2
  selector:
    app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: node-app
        image: yulypso/node-app
        ports:
        - containerPort: 3000