apiVersion: v1
kind: Service
metadata:
   name: node-app-service
   labels:
      app: my-node-app
spec:
   ports:
   - port: 80
     targetPort: nodejs-port
     protocol: TCP
   selector:
     app: my-node-app
   type: LoadBalancer 
  